sudo: required
services: 
  - docker
before_install:
  - docker build -t tuannthnvn/blog-test -f Dockerfile.dev ./client

script:
  - docker run tuannthnvn/blog-test npm run test -- --coverage

after_success:
  - docker build -t tuannthnvn/blog-be ./be
  - docker build -t tuannthnvn/blog-fe ./fe
  - docker build -t tuannthnvn/blog-nginx ./nginx
  #Login to Docker hub through Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  #Take those images and push them to Docker Hub
  - docker push tuannthnvn/blog-be
  - docker push tuannthnvn/blog-fe
  - docker push tuannthnvn/blog-nginx
