version: "3.7"
services:
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
  mongo:
    image: mongo
    restart: always
  redis:
    image: redis:alpine
    restart: always
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./be 
    volumes:
      - /app/node_modules
      - ./be:/app
    environment:
      - JWT_SECRET=tuan.nguyen4
      - MONGO_URI=mongodb://mongo:27017/blog
      - REDIS_URI=redis://redis:6379
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./fe
    volumes:
      - /app/node_modules
      - ./fe:/app