version: "3.7"
services:
  database:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  backend:
    image: node
    restart: always
    volumes:
      - ./be:/usr/src/backend
      - ./usr/src/backend/node_modules
    command: bash -c "cd /usr/src/backend && npm i -g nodemon && npm i && npm start"
    ports: 
      - "4000:4000"
    links:
      - database:database
  frontend:
    image: node
    restart: always
    volumes:
      - ./fe:/usr/src/frontend
      - ./usr/src/frontend/node_modules
    command: bash -c "cd /usr/src/frontend && npm i && npm start"
    ports:
      - "3000:3000"

  
